name: CI
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  my_build_job:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: npm install, test and build
        run: |
          npm install
          npm run build
      - name: Run a one line script
        run: echo Hellow, world
      - name: Run a multi-line script
        run: |
            echo add other actions to build,
            echo test, and deploy your project.
      - name: Run js file for test
        run: node js/script.js
      
